---
- name: Install Nano
  package:
    name: "nano"
    state: installed
  become: yes
  
- name: Install Wget
  package:
    name: "wget"
    state: installed
  become: yes

- name: Install Unzip
  package:
    name: "unzip"
    state: installed
  become: yes

- name: Install dumb init
  get_url:
    dest: /usr/bin/dumb-init
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    mode: 0775
    validate_certs: no
  become: yes

- name: Install epel
  yum:
    name: epel-release
    state: present
    disable_gpg_check: yes
  become: yes

- name: Create app user
  user:
    name: usr_app
    uid: 1000
    group: root
    state: present
    createhome: yes
    home: "/usr_app"

- name: Copy source into container
  synchronize:
    src: "roles/glpi/files/index.php"
    dest: "/var/www/"
  remote_user: usr_app