---
# - name: Copy cnf file that makes MyISAM the default engine (required by GLPI)
#   copy:
#     src: files/server.cnf
#     dest: /etc/my.cnf.d/server.cnf
#     owner: root
#     group: root
#     mode: 0644
#   become: yes

# - name: Copy shell script backup file used by crontab
#   copy:
#     src: files/{{ mariadb_sh_bkp_file }}
#     dest: /usr/local/sbin/{{ mariadb_sh_bkp_file }}
#     owner: root
#     group: root
#     mode: 0644
#   become: yes

# # Generates warning message and always changed output
# - name: Ensure service is started 
#   shell: service mysql start
#   become: yes
#   args:
#     warn: False