---
- name: Add official MariaDB repository
  yum_repository:
    name: MariaDB
    description: Official MariaDB repository
    baseurl: "http://{{ mariadb_mirror }}/{{ mariadb_version }}/{{ ansible_distribution|lower|regex_replace('redhat', 'rhel')|regex_replace('oraclelinux', 'centos') }}{{ ansible_distribution_major_version }}-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
  tags: mariadb
  become: yes

- name: Install MariaDB packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mariadb_packages }}"
  tags: mariadb
  become: yes

# - name: Install accurate server time packages with NTP (Network Time Protocol)
#   yum:
#     name:
#       - ntp
#       - ntpdate
#     state: present
#   become: yes